# Guide on setting up GPG in MacOs
# https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e

git:
  defaults:
    name: Roberto Mora
    email: romogo17@gmail.com
    signingkey: 9F6D8C373B40B768
  work:
    name: Mora, Roberto
    email: Roberto.Mora@experian.com
    signingkey: 9F6D8C373B40B768
    dirs:
      - WDev
      - Work
