live_config_reload: true

env:
  TERM: xterm-256color

font:
  normal:
    family: "Fira Code"
    style: Medium
  size: 15

window:
  opacity: 0.9
  dimensions:
    columns: 120
    lines: 40
  padding:
    x: 15
    y: 15

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"

key_bindings:
  # Terminal file manager
  - { key: F, mods: Command, chars: "lfcd\n" }
  # Select a new tmux session for the attached client interactively
  - { key: S, mods: Command|Shift, chars: "\x02s" }
  # Switch to last tmux session (tmux=^BL)
  - { key: L, mods: Command|Shift, chars: "\x02L" }
  # Switch to last tmux window (tmux=^B^B)
  - { key: L, mods: Command, chars: "\x02\x02" }

  # Select window 1-9
  - { key: Key1, mods: Command, chars: "\x021" }
  - { key: Key2, mods: Command, chars: "\x022" }
  - { key: Key3, mods: Command, chars: "\x023" }
  - { key: Key4, mods: Command, chars: "\x024" }
  - { key: Key5, mods: Command, chars: "\x025" }
  - { key: Key6, mods: Command, chars: "\x026" }
  - { key: Key7, mods: Command, chars: "\x027" }
  - { key: Key8, mods: Command, chars: "\x028" }
  - { key: Key9, mods: Command, chars: "\x029" }

  # Create a new tmux window (tmux=^Bc)
  - { key: T, mods: Command, chars: "\x02c" }

  # Rename the current tmux window (tmux=^B,)
  - { key: Comma, mods: Command, chars: "\x02," }
  # Rename the current tmux session (tmux=^B$)
  - { key: Period, mods: Command, chars: "\x02$" }

  # Change to the previous tmux window (tmux=^Bp}
  - { key: LBracket, mods: Command|Shift, chars: "\x02p" }
  # Change to the next tmux window (tmux=^Bn)
  - { key: RBracket, mods: Command|Shift, chars: "\x02n" }

  # Split the current pane into two, left and right (tmux=^B%)
  - { key: N, mods: Command|Shift, chars: "\x02%" }
  # Split the current pane into two, top and bottom (tmux=^B")
  - { key: N, mods: Command, chars: "\x02\"" }

  # Select panes with arrows
  - { key: Left, mods: Command|Shift, chars: "\x02h" }
  - { key: Down, mods: Command|Shift, chars: "\x02j" }
  - { key: Up, mods: Command|Shift, chars: "\x02k" }
  - { key: Right, mods: Command|Shift, chars: "\x02l" }

  # Kill the current tmux pane (and window if last pane) (tmux=^Bx)
  - { key: W, mods: Command, chars: "\x02x" }
  # Detach the current tmux client (tmux=^Bd)
  - { key: D, mods: Command, chars: "\x02d" }

  # Move cursor one word forward/backward
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

  # Move cursor to the begining/end of line
  - { key: Left, mods: Command, chars: "\x01" }
  - { key: Right, mods: Command, chars: "\x05" }

  # Break the current tmux pane out of the tmux window (tmux=^B!)
  - { key: T, mods: Command|Shift, chars: "\x02!" }
  # Toggle the zoom state of the current tmux pane (tmux=^Bz)
  - { key: Z, mods: Command, chars: "\x02z" }
  # Enter copy mode (tmux=^B[)
  - { key: LBracket, mods: Command, chars: "\x02[" }

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

colors:
  # Default colors
  primary:
    background: "0x1b182c"
    foreground: "0xcbe3e7"

  # Normal colors
  normal:
    black: "0x100e23"
    red: "0xff8080"
    green: "0x95ffa4"
    yellow: "0xffe9aa"
    blue: "0x91ddff"
    magenta: "0xc991e1"
    cyan: "0xaaffe4"
    white: "0xcbe3e7"

  # Bright colors
  bright:
    black: "0x565575"
    red: "0xff5458"
    green: "0x62d196"
    yellow: "0xffb378"
    blue: "0x65b2ff"
    magenta: "0x906cff"
    cyan: "0x63f2f1"
    white: "0xa6b3cc"
