live_config_reload: true

import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

env:
  TERM: xterm-256color

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 17.5

window:
  dimensions:
    columns: 120
    lines: 40

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"

key_bindings:
  # Select a new tmux session for the attached client interactively (tmux=^Space + s)
  - { key: S, mods: Command|Shift, chars: "\x00s" }
  # Switch to last tmux session (tmux=^Space + L)
  - { key: L, mods: Command|Shift, chars: "\x00L" }
  # Switch to last tmux window (tmux=^Space + l)
  - { key: L, mods: Command, chars: "\x00l" }

  # Select window 1-9
  - { key: Key1, mods: Command, chars: "\x001" }
  - { key: Key2, mods: Command, chars: "\x002" }
  - { key: Key3, mods: Command, chars: "\x003" }
  - { key: Key4, mods: Command, chars: "\x004" }
  - { key: Key5, mods: Command, chars: "\x005" }
  - { key: Key6, mods: Command, chars: "\x006" }
  - { key: Key7, mods: Command, chars: "\x007" }
  - { key: Key8, mods: Command, chars: "\x008" }
  - { key: Key9, mods: Command, chars: "\x009" }

  # Create a new tmux window (tmux=^Space+c)
  - { key: T, mods: Command, chars: "\x00c" }

  # Rename the current tmux window (tmux=^Space + ,)
  - { key: Comma, mods: Command, chars: "\x00," }
  # Rename the current tmux session (tmux=^Space + $)
  - { key: Period, mods: Command, chars: "\x00$" }

  # Change to the previous tmux window (tmux=^Space + p}
  - { key: LBracket, mods: Command|Shift, chars: "\x00p" }
  # Change to the next tmux window (tmux=^Space + n)
  - { key: RBracket, mods: Command|Shift, chars: "\x00n" }

  # Split the current pane into two, left and right (tmux=^Space + %)
  - { key: N, mods: Command|Shift, chars: "\x00%" }
  # Split the current pane into two, top and bottom (tmux=^Space + ")
  - { key: N, mods: Command, chars: "\x00\"" }

  # Select panes with arrows
  - { key: Left, mods: Command|Shift, chars: "\x00h" }
  - { key: Down, mods: Command|Shift, chars: "\x00j" }
  - { key: Up, mods: Command|Shift, chars: "\x00k" }
  - { key: Right, mods: Command|Shift, chars: "\x00l" }

  # Kill the current tmux pane (and window if last pane) (tmux=^Space + x)
  - { key: W, mods: Command, chars: "\x00x" }
  # Detach the current tmux client (tmux=^Space + d)
  - { key: D, mods: Command, chars: "\x00d" }

  # Move cursor one word forward/backward
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

  # Move cursor to the begining/end of line
  - { key: Left, mods: Command, chars: "\x01" }
  - { key: Right, mods: Command, chars: "\x05" }

  # Clear the screen (tmux=^Space + ^l)
  - { key: K, mods: Command, chars: "\x00\x0c" }

  # Break the current tmux pane out of the tmux window (tmux=^Space + !)
  - { key: T, mods: Command|Shift, chars: "\x00!" }
  # Toggle the zoom state of the current tmux pane (tmux=^Space + z)
  - { key: Z, mods: Command, chars: "\x00z" }
  # Enter copy mode (tmux=^Space + [)
  - { key: LBracket, mods: Command, chars: "\x00[" }

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true
