ansible_config:
  - section: defaults
    option: host_key_checking
    value: False
  - section: defaults
    option: stdout_callback
    value: yaml
  - section: defaults
    option: timeout
    value: 60
  - section: defaults
    option: bin_ansible_callbacks
    value: True
  - section: defaults
    option: interpreter_python
    value: auto_silent

  - section: galaxy
    option: server_list
    value: release_galaxy

  - section: galaxy_server.release_galaxy
    option: url
    value: https://galaxy.ansible.com/

  - section: ssh_connection
    option: transfer_method
    value: scp
