- name: Close any open System Preferences panes
  shell: |-
    osascript -e 'tell application "System Preferences" to quit'

- name: Always show scrollbars. Possible values are WhenScrolling, Automatic and Always
  community.general.osx_defaults:
    key: AppleShowScrollBars
    value: "Always"

- name: Increase window resize speed for Cocoa applications
  community.general.osx_defaults:
    key: NSWindowResizeTime
    type: float
    value: 0.001

- name: Expand save panel by default
  community.general.osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true

- name: Expand save panel by default (2)
  community.general.osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true

- name: Expand print panel by default
  community.general.osx_defaults:
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true

- name: Expand print panel by default (2)
  community.general.osx_defaults:
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true

- name: Save to disk (not to iCloud) by default
  community.general.osx_defaults:
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false

- name: Automatically quit printer app once the print jobs complete
  community.general.osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true

- name: Disable the “Are you sure you want to open this application?” dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

- name: Trackpad - enable tap to click for this user and for the login screen
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1

- name: Trackpad - enable tap to click for this user and for the login screen (currentHost)
  community.general.osx_defaults:
    host: currentHost
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

- name: Trackpad - enable tap to click for this user and for the login screen
  community.general.osx_defaults:
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

- name: Increase sound quality for Bluetooth headphones/headsets
  community.general.osx_defaults:
    domain: com.apple.BluetoothAudioAgent
    key: "Apple Bitpool Min (editable)"
    type: int
    value: 40

- name: Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
  community.general.osx_defaults:
    key: AppleKeyboardUIMode
    type: int
    value: 3

- name: Set languages
  community.general.osx_defaults:
    key: AppleLanguages
    type: array
    value:
      - en
      - es

- name: Set locale and currency
  community.general.osx_defaults:
    key: AppleLocale
    value: "en_US@currency=USD"

- name: Set measurement units
  community.general.osx_defaults:
    key: AppleMeasurementUnits
    value: "Centimeters"

- name: Use metric units
  community.general.osx_defaults:
    key: AppleMetricUnits
    type: bool
    value: true

- name: Save screenshots to the desktop
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: "$HOME/Desktop"

- name: Save screenshots in PNG format (other options are BMP, GIF, JPG, PDF, TIFF)
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    value: "png"

- name: Enable subpixel font rendering on non-Apple LCDs (reference https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleFontSmoothing
    type: int
    value: 1

# Alternate command that takes care of the following task
#   sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true
- name: Enable HiDPI display modes (requires restart)
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.windowserver
    key: DisplayResolutionEnabled
    type: bool
    value: true
  become: true
  tags:
    - privileged

- name: Show icons for hard drives on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true

- name: Show icons for hard drives on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: false

- name: Show mounted servers on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: false

- name: Show removable media on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true

- name: Finder - show status bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: Finder - show path bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: Keep folders on top when sorting by name
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true

- name: When performing a search, search the current folder by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    value: "SCcf"

- name: Disable the warning when changing a file extension
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Enable spring loading for directories
  community.general.osx_defaults:
    key: com.apple.springing.enabled
    type: bool
    value: true

- name: Remove the spring loading delay for directories
  community.general.osx_defaults:
    key: com.apple.springing.delay
    type: float
    value: 0.5

- name: Avoid creating .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: write com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Avoid creating .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: write com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

- name: Disable disk image verification
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify
    type: bool
    value: true

- name: Disable disk image verification (locked)
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-locked
    type: bool
    value: true

- name: Disable disk image verification (remote)
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-remote
    type: bool
    value: true

- name: Automatically open a new Finder window when a volume is mounted (RO)
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-ro-root
    type: bool
    value: true

- name: Automatically open a new Finder window when a volume is mounted (RW)
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-rw-root
    type: bool
    value: true

- name: Automatically open a new Finder window when a volume is mounted
  community.general.osx_defaults:
    domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    type: bool
    value: true

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  shell: |-
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

- name: Use list view in all Finder windows by default. Four-letter codes for the other view modes 'icnv', 'clmv', 'glyv'
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"

- name: Disable the warning before emptying the Trash
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

- name: Enable AirDrop over Ethernet and on unsupported Macs running Lion
  community.general.osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true

- name: Show the ~/Library folder
  shell: |-
    chflags nohidden ~/Library

- name: Show the /Volumes folder
  shell: |-
    chflags nohidden /Volumes
  become: true
  tags:
    - privileged

- name: Enable highlight hover effect for the grid view of a stack (Dock)
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mouse-over-hilite-stack
    type: bool
    value: true

- name: Set the icon size of Dock items to 40 pixels
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 40

- name: Enable dock magnification
  community.general.osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: true

- name: Set magnification icon size to 60 pixels
  community.general.osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: int
    value: 60

- name: Minimize windows into their application's icon
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true

- name: Show indicator lights for open applications in the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true

- name: Speed up Mission Control animations
  community.general.osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.1

- name: Don't group windows by application in Mission Control (i.e. use the old Exposé behavior instead)
  community.general.osx_defaults:
    domain: com.apple.dock
    key: expose-group-by-app
    type: bool
    value: false

- name: Remove the auto-hiding Dock delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0

# - name: Remove the animation when hiding/showing the Dock
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: autohide-time-modifier
#     type: float
#     value: 0

- name: Automatically hide and show the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: Make Dock icons of hidden applications translucent
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true

# - name: Don't show recent applications in Dock
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: show-recents
#     type: bool
#     value: false

- name: Change indexing order and disable some search results
  community.general.osx_defaults:
    domain: com.apple.spotlight
    key: orderedItems
    type: array
    value:
      - '{"enabled" = 1;"name" = "APPLICATIONS";}'
      - '{"enabled" = 1;"name" = "SYSTEM_PREFS";}'
      - '{"enabled" = 1;"name" = "DIRECTORIES";}'
      - '{"enabled" = 1;"name" = "PDF";}'
      - '{"enabled" = 1;"name" = "FONTS";}'
      - '{"enabled" = 0;"name" = "DOCUMENTS";}'
      - '{"enabled" = 0;"name" = "MESSAGES";}'
      - '{"enabled" = 0;"name" = "CONTACT";}'
      - '{"enabled" = 0;"name" = "EVENT_TODO";}'
      - '{"enabled" = 0;"name" = "IMAGES";}'
      - '{"enabled" = 0;"name" = "BOOKMARKS";}'
      - '{"enabled" = 0;"name" = "MUSIC";}'
      - '{"enabled" = 0;"name" = "MOVIES";}'
      - '{"enabled" = 0;"name" = "PRESENTATIONS";}'
      - '{"enabled" = 0;"name" = "SPREADSHEETS";}'
      - '{"enabled" = 0;"name" = "SOURCE";}'
      - '{"enabled" = 0;"name" = "MENU_DEFINITION";}'
      - '{"enabled" = 0;"name" = "MENU_OTHER";}'
      - '{"enabled" = 0;"name" = "MENU_CONVERSION";}'
      - '{"enabled" = 0;"name" = "MENU_EXPRESSION";}'
      - '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}'
      - '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'

- name: Rebuild the index
  shell: |-
    # Load new settings before rebuilding the index
    killall mds > /dev/null 2>&1
    # Make sure indexing is enabled for the main volume
    mdutil -i on / > /dev/null
    # Rebuild the index from scratch
    mdutil -E / > /dev/null
  become: yes
  tags:
    - privileged

- name: Use plain text mode for new TextEdit documents
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0

- name: Open and save files as UTF-8 in TextEdit
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4

- name: Open and save files as UTF-8 in TextEdit (for write)
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4

- name: Prevent Photos from opening automatically when devices are plugged in
  community.general.osx_defaults:
    domain: com.apple.ImageCapture
    key: disableHotPlug
    host: currentHost
    type: bool
    value: true

- name: Kill some of the processes that need to be restarted
  shell: |-
    for app in "cfprefsd" \
      "Dock" \
      "Finder" \
      "Photos" \
      "SystemUIServer" \
      "Terminal" ; do
      killall "${app}" &> /dev/null
    done
    echo "Done. Note that some of these changes require a logout/restart to take effect."
