- name: Ensure Taps are installed
  community.general.homebrew_tap:
    name: "{{ item.name }}"
    state: present
  loop: "{{ brew_taps }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure the Homebrew packages are installed
  community.general.homebrew:
    name: "{{ item.name }}"
    state: present
  loop: "{{ brew_packages }}"
  loop_control:
    label: "{{ item.name }}: {{ item.about }}"

- name: Create directories where symlinks are going to be created
  ansible.builtin.file:
    dest: "{{ item.1.dest | dirname }}"
    state: directory
    mode: 0755
  loop: "{{ brew_packages | json_query('[?links]') | subelements('links') }}"
  loop_control:
    label: "{{ item.0.name }}: {{ item.1.dest | dirname }}"

- name: Create any additional symlinks needed
  ansible.builtin.file:
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    state: link
    force: yes
  loop: "{{ brew_packages | json_query('[?links]') | subelements('links') }}"
  loop_control:
    label: "{{ item.0.name }}: {{ item.1.dest }} -> {{ item.1.src }}"

- name: Ensure the Homebrew casks are installed
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: present
  loop: "{{ brew_casks }}"
  loop_control:
    label: "{{ item.name }}: {{ item.about }}"
