# Taps
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "bazelbuild/tap"

# Utilities
brew "coreutils" # Those that come with macOS are outdated
brew "moreutils"
brew "findutils"
brew "bash" # Latest Bash version
brew "bash-completion"
brew "wget"
brew "vim"
brew "grep"
brew "gnupg"
brew "pinentry-mac" # needed as gpg agent
brew "bat" # "cat" on steroids
brew "youtube-dl"
brew "telnet"
brew "watchman"
brew "tesseract-lang"
brew "ffmpeg"
brew "zlib"
brew "pandoc"
brew "httpie"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "mackup"
brew "trash" # Manage trash bin
brew "mas" # Mac App Store manager
brew "tree" # List directories in a tree structure
brew "hyperfine" # A command-line benchmarking tool.
brew "asciinema" # Solution for recording terminal sessions and sharing them on the web.

# Navigation and search
brew "autojump"
brew "fd"
brew "fzf"

# Brew services
brew "postgresql"
brew "redis"

# Git
brew "git"
brew "git-lfs"
brew "git-flow"
brew "hub" # A command-line tool that makes git easier to use with GitHub
brew "gh" # GitHub’s official command line tool

# Cloud Native
brew "kubernetes-cli"
brew "openshift-cli"
brew "awscli"

# Development
brew "ansible"
brew "terraform"
brew "yarn"
brew "autoconf"
brew "automake"
brew "pkg-config"
brew "clang-format"
brew "protobuf"
brew "golang"
brew "boost"
brew "bazelbuild/tap/bazel"
brew "kompose"
brew "kops"
brew "minikube"

# Apps
cask "minishift"
cask "hyper"
cask "1password"
cask "docker"
cask "the-unarchiver"
# cask "google-backup-and-sync"
# cask "google-chrome"
# cask "slack"
# cask "alfred"
# cask "bartender"
# cask "caffeine"
# cask "imageoptim"
# cask "postman"

# Quicklook
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"

# Mac App Store
mas "Magnet", id: 441258766
# mas "Spark", id: 1176895641 # https://sparkmailapp.com/
# mas "Things", id: 904280696 # https://culturedcode.com/things/

