- name: Ensure Bash is installed
  community.general.homebrew:
    name:
      - bash
      - bash-completion
    state: present

- name: Ensure Fish and Starship are installed
  community.general.homebrew:
    name:
      - fish
      - starship
    state: present

# - name: Ensure ZSH is installed
#   community.general.homebrew:
#     name:
#       - zsh
#       - zsh-completions
#       - zsh-syntax-highlighting
#     state: present

# Alternate commands that take care of the following tasks
#   echo $(brew --prefix)/bin/fish | sudo tee -a /etc/shells
#   chsh -s $(brew --prefix)/bin/fish
- name: Setup Fish as the default shell for the user
  become: true
  block:
    - name: Ensure Fish is a valid shell
      ansible.builtin.lineinfile:
        path: /etc/shells
        state: present
        line: "{{ brew_prefix }}/bin/fish"
    - name: Setup the default shell for the {{ ansible_env.USER }} user
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: "{{ brew_prefix }}/bin/fish"
  tags:
    - privileged

- name: Ensure the configuration directory for Fish exists
  ansible.builtin.file:
    path: ~/.config/fish
    state: directory
    mode: 0755

- name: Copy the Fish configuration
  ansible.builtin.copy:
    dest: ~/.config/fish
    src: fish/
    mode: 0644

- name: Copy the Starship configuration
  ansible.builtin.copy:
    dest: ~/.config
    src: starship/
    mode: 0644

- name: Install FZF
  command: "{{ brew_prefix }}/opt/fzf/install --no-zsh --no-bash --all"
  changed_when: false
