- name: Ensure terminal tools are installed
  community.general.homebrew:
    name:
      - bash
      - bash-completion
      - fish
      - starship
      - tmux
      - tmux-mem-cpu-load
    state: present

# Alternate commands that take care of the following tasks
#   echo $(brew --prefix)/bin/fish | sudo tee -a /etc/shells
#   chsh -s $(brew --prefix)/bin/fish
- name: Setup Fish as the default shell for the user
  become: true
  tags: privileged
  block:
    - name: Ensure Fish is a valid shell
      ansible.builtin.lineinfile:
        path: /etc/shells
        state: present
        line: "{{ brew_prefix }}/bin/fish"
    - name: Setup the default shell for {{ ansible_env.USER }}
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: "{{ brew_prefix }}/bin/fish"

- name: Fish configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/fish"
    dest: ~/.config/fish
    state: link
    force: true
    mode: 0755

- name: Starship configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/starship/starship.toml"
    dest: ~/.config/starship.toml
    state: link
    force: true
    mode: 0644

- name: Install FZF
  ansible.builtin.command: "{{ brew_prefix }}/opt/fzf/install --no-zsh --no-bash --all"
  args:
    creates: ~/.config/fish/functions/fzf_key_bindings.fish

- name: Ghostty configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/ghostty"
    dest: ~/.config/ghostty
    state: link
    force: true
    mode: 0755

- name: Alacritty configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/alacritty"
    dest: ~/.config/alacritty
    state: link
    force: true
    mode: 0755

- name: Tmux Plugin Manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    depth: 1
  tags:
    - skip_ansible_lint

- name: Tmux configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux"
    dest: ~/.config/tmux
    state: link
    force: true
    mode: 0755

- name: GnuPG configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/gnupg"
    dest: ~/.gnupg
    state: link
    force: true
    mode: 0700

- name: SSH configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/ssh"
    dest: ~/.ssh
    state: link
    force: true
    mode: 0700
