- name: Create directories
  ansible.builtin.file:
    path: "{{ config.dest_dir }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ config.src_dir }}"
  when: item.state == 'directory'

- name: Create symlinks
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ config.dest_dir }}/{{ item.path }}"
    state: link
    follow: false # avoid corrupting target files if the link already exists
    force: true
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ config.src_dir }}"
  when: item.state == 'file'
